server:
  port: 8091

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/