server:
  port: 8092

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/

resilience4j:
  circuitbreaker:
    instances:
      productClient:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10